server:
  port: 80

spring:
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/static/
    suffix: .html

#spring:
  application:
    name: wangyikaola-consumer

eureka:
    client:
      register-with-eureka: true
      service-url:
        defaultZone: http://eureka6001.com:6001/eureka/
    instance:
      instance-id: wangyikaola-consumer-80
      prefer-ip-address: true     #访问路径可以显示IP地址
feign:
  hystrix:
    enabled: false  #这里说一下超时的原因 Hystrix熔断器检测时间（默认1秒） 通过“圈一”可以看出上图超出了1mm。 应为true，但此处直接禁用Feign里面的Hystrix